system:
  env: "dev"
  logConfig:
    filename: "log/system/log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"
token:
  signingKey: "e199ad17-c090-43cb-b095-1dc55c209a77"
  expiresTime: 604800
gin:
  mode: release
  host: "0.0.0.0"
  port: "8080"
  logConfig:
    filename: "log/gin/log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"
login:
  github:
    clientId: "97bc323362f96abbc3d3"
    clientSecret: "f4c82475993cebf0a259750f537aec3d17004dcc"
    redirectUri: "http://localhost:8080/callback"
    scope: "user:email"
  google:
    redirectUri: "http://localhost:8080/callback"
    scope: "user:email"
email:
  from: "907090585@qq.com"
  password: "cvxjaeubymkxbbic"
  host: "smtp.qq.com"
imaging:
  width: 400
  height: 0
  blur: 2
