system:
  env: "dev"
  logConfig:
    filename: "log/system/system.log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"
token:
  accessToken:
    signingKey: "e199ad17-c090-43cb-b095-1dc55c209a77"
    expiresTime: 1
  refreshToken:
    signingKey: "e199ad17-c090-43cb-b095-1dc55c209a77"
    expiresTime: 168
bucket:
  fillInterval: 10
  quantum: 10
  capacity: 10000
  waitTime: 3
gin:
  mode: release
  host: "0.0.0.0"
  port: "8080"
  logConfig:
    filename: "log/gin/gin.log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"
login:
  github:
    clientId: "97bc323362f96abbc3d3"
    clientSecret: "f4c82475993cebf0a259750f537aec3d17004dcc"
    redirectUri: "http://localhost:8080/callback"
    scope: "user:email"
  google:
    redirectUri: "http://localhost:8080/callback"
    scope: "user:email"
email:
  qqEmail:
    from: "2026499232@qq.com"
    password: "ndzqxcvuekkkdjhd"
    host: "smtp.qq.com"
  gmail:
    from: "xyleigp@gmail.com"
    password: "dyshkcrrlsdwyhhh"
    host: "smtp.gmail.com"
imaging:
  width: 400
  height: 0
  blur: 2
snowFlake:
  snowFlakeMachineId: 1