mysql:
  host: "1.117.141.66"
  port: 3306
  charset: "utf8"
  username: "root"
  password: "123456abc"
  setMaxIdleConns: 10
  setMaxOpenConns: 128
  setConnMaxLifetime: 60
  db: "img"
  slowThreshold: 30
  logConfig:
    filename: "log/mysql/log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"
redis:
  addr: "1.117.141.66:6379"
  password: "123456abc"
  db: 0
  poolSize: 50
  logConfig:
    filename: "log/mysql/log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"

nsq:
  nsqdAddr: "1.117.141.66:4150"
  nsqlookupdAddr: "1.117.141.66:4161"
socket:
  mode: release
  host: "0.0.0.0"
  port: "8000"
  readBufferSize: 1024
  writeBufferSize: 1024
  handshakeTimeout: 10s
  enableCompression: true
elasticsearch:
  addr: "http://1.117.141.66:9200"
  username: "elastic"
  password: "123456abc"